version: "2"

services:
  mysql-local:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./Docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=devadmin
      - MYSQL_ROOT_PASSWORD=devadmin
